# typed: false
# frozen_string_literal: true

# This file was generated by scripts/update-package-managers.sh. Do not edit manually.
class Razorpay < Formula
  desc "Official Razorpay CLI."
  homepage "https://github.com/razorpay/razorpay-cli"
  version "1.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://razorpay.com/cli/latest/razorpay_mac-os_arm64.tar.gz"
      sha256 "1b36bec1d7b11dc204c863a336ea1af38ef492fed86c31c9337800459b1827d5"
    else
      url "https://razorpay.com/cli/latest/razorpay_mac-os_x86_64.tar.gz"
      sha256 "116b7b44d7ad3a6be6d435ca86fba26ad36d4aef52b629e024daa36fc43b8b27"
    end
  end

  def install
    bin.install "razorpay"
  end

  def caveats
    <<~EOS
      Thanks for installing the Razorpay CLI! If this is your first time using the CLI, be sure to run `razorpay configure` first.
    EOS
  end

  test do
    assert_match "razorpay version", shell_output("#{bin}/razorpay --version")
  end
end
