# typed: false
# frozen_string_literal: true

# This file was generated by scripts/update-package-managers.sh. Do not edit manually.
class Razorpay < Formula
  desc "Official Razorpay CLI."
  homepage "https://github.com/razorpay/razorpay-cli"
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://razorpay.com/cli/latest/razorpay_mac-os_arm64.tar.gz"
      sha256 "af10bc350e8ec7df9d81a52650b5b69dbf234fdeed2a98178dec2aa4435a9257"
    else
      url "https://razorpay.com/cli/latest/razorpay_mac-os_x86_64.tar.gz"
      sha256 "2d0c15dd5c2291462409c0580a9d619509736af079d2ee0007230d7edb1e9f3c"
    end
  end

  def install
    bin.install "razorpay"
  end

  def caveats
    <<~EOS
      Thanks for installing the Razorpay CLI! If this is your first time using the CLI, be sure to run `razorpay configure` first.
    EOS
  end

  test do
    assert_match "razorpay version", shell_output("#{bin}/razorpay --version")
  end
end
