# typed: false
# frozen_string_literal: true

# This file was generated by scripts/update-package-managers.sh. Do not edit manually.
class Razorpay < Formula
  desc "Official Razorpay CLI."
  homepage "https://github.com/razorpay/razorpay-cli"
  version "1.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://razorpay.com/cli/latest/razorpay_mac-os_arm64.tar.gz"
      sha256 "8c289949abb0092d82d6e79cff2e51d919824c18903cc9fdb4a95f453ba77b10"
    else
      url "https://razorpay.com/cli/latest/razorpay_mac-os_x86_64.tar.gz"
      sha256 "0010317489129ccb50b48fb0d69f8332a2088d857efd2854dc7900341892ae33"
    end
  end

  def install
    bin.install "razorpay"
  end

  def caveats
    <<~EOS
      Thanks for installing the Razorpay CLI! If this is your first time using the CLI, be sure to run `razorpay configure` first.
    EOS
  end

  test do
    assert_match "razorpay version", shell_output("#{bin}/razorpay --version")
  end
end
